environment: production

backend:
  replicaCount: 3

  image:
    repository: "ghcr.io/ridhampansara27/cloudops-insight-backend"
    tag: "not-deployed-yet"
    pullPolicy: IfNotPresent

frontend:
  replicaCount: 3

  image:
    repository: "ghcr.io/ridhampansara27/cloudops-insight-frontend"
    tag: "not-deployed-yet"
    pullPolicy: IfNotPresent

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  className: nginx
  host: cloudops.example.com

secrets:
  existingSecret: cloudops-secrets