# Identify the EKS development environment.
environment: dev


# ------------------------------------------------------------
# Backend
# ------------------------------------------------------------

backend:
  # Run two backend replicas in EKS.
  replicaCount: 2

  image:
    # Pull the backend image from GitHub Container Registry.
    repository: "ghcr.io/ridhampansara27/cloudops-insight-backend"

    # Use the existing immutable application image.
    tag: "sha-340cbacd128a114f9c4592e95de6153c3c101198"

    # Reuse the locally cached image when available.
    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# Frontend
# ------------------------------------------------------------

frontend:
  # Run two frontend replicas in EKS.
  replicaCount: 2

  image:
    # Pull the frontend image from GitHub Container Registry.
    repository: "ghcr.io/ridhampansara27/cloudops-insight-frontend"

    # Use the same immutable application build currently used by dev.
    tag: "sha-340cbacd128a114f9c4592e95de6153c3c101198"

    # Reuse the locally cached image when available.
    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# AWS Application Load Balancer
# ------------------------------------------------------------

ingress:
  enabled: true

  # Use AWS Load Balancer Controller.
  className: alb

  # No Route53 DNS name yet.
  host: ""

  annotations:

    # Create a public ALB.
    alb.ingress.kubernetes.io/scheme: internet-facing

    # Send ALB traffic directly to Pod IP addresses.
    alb.ingress.kubernetes.io/target-type: ip

    # Use HTTP for this short-lived demonstration.
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

    # Health-check the frontend NGINX endpoint.
    alb.ingress.kubernetes.io/healthcheck-path: /healthz

    # Tag the generated ALB for cleanup and cost visibility.
    alb.ingress.kubernetes.io/tags: Project=cloudops-insight,Environment=dev,Temporary=true


# ------------------------------------------------------------
# Autoscaling
# ------------------------------------------------------------

autoscaling:
  enabled: true

  minReplicas: 2

  maxReplicas: 4

  targetCPUUtilizationPercentage: 70


# ------------------------------------------------------------
# Existing runtime Secret
# ------------------------------------------------------------

secrets:
  existingSecret: cloudops-secrets