{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  # Create the CloudOps public application ingress.
  name: cloudops-insight

  {{- with .Values.ingress.annotations }}

  # Render environment-specific ingress-controller configuration.
  annotations:
{{ toYaml . | indent 4 }}

  {{- end }}

spec:
  # Select nginx locally or ALB in EKS.
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    -
      {{- if .Values.ingress.host }}

      # Add a DNS host only when one is configured.
      host: {{ .Values.ingress.host | quote }}

      {{- end }}

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                # Send traffic to frontend NGINX.
                name: cloudops-frontend

                port:
                  number: 8080

{{- end }}