{{- if .Values.postgresBackup.uploadSecret.enabled }}
{{- $secretName := required "postgresBackup.uploadSecret.name is required" .Values.postgresBackup.uploadSecret.name }}
{{- $encryptedParUrl := required "postgresBackup.uploadSecret.encryptedParUrl is required when uploadSecret is enabled" .Values.postgresBackup.uploadSecret.encryptedParUrl }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: {{ $secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}

  labels:
    app.kubernetes.io/name: cloudops-insight
    app.kubernetes.io/component: postgres-backup
    app.kubernetes.io/managed-by: Helm

spec:
  encryptedData:
    par-url: {{ $encryptedParUrl | quote }}

  template:
    metadata:
      name: {{ $secretName | quote }}
      namespace: {{ .Release.Namespace | quote }}

      labels:
        app.kubernetes.io/name: cloudops-insight
        app.kubernetes.io/component: postgres-backup

    type: Opaque
{{- end }}
