# Identify deployment environment.
environment: dev


# ------------------------------------------------------------
# Backend
# ------------------------------------------------------------

backend:
  replicaCount: 2

  image:
    # Start using the Kind-loaded local image.
    # GitHub Actions will replace this after the first GHCR deployment.
    repository: "ghcr.io/ridhampansara27/cloudops-insight-backend" # backend-image-repository

    tag: "sha-29b74b5a8413d474159657dba85047710a0b7bf5" # backend-image-tag

    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# Frontend
# ------------------------------------------------------------

frontend:
  replicaCount: 2

  image:
    repository: "ghcr.io/ridhampansara27/cloudops-insight-frontend" # frontend-image-repository

    tag: "sha-29b74b5a8413d474159657dba85047710a0b7bf5" # frontend-image-tag

    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# Application ingress
# ------------------------------------------------------------

ingress:
  enabled: true

  className: nginx

  host: cloudops.local


# ------------------------------------------------------------
# Development autoscaling
# ------------------------------------------------------------

autoscaling:
  enabled: true

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 70


# ------------------------------------------------------------
# Existing manually-created Kubernetes Secret
# ------------------------------------------------------------

secrets:
  existingSecret: cloudops-secrets
