# Identify deployment environment.
environment: dev


# ------------------------------------------------------------
# Backend
# ------------------------------------------------------------

backend:
  replicaCount: 2

  image:
    # Start using the Kind-loaded local image.
    # GitHub Actions will replace this after the first GHCR deployment.
    repository: "ghcr.io/ridhampansara27/cloudops-insight-backend"

    tag: "sha-81bf32d3ecb99cbe500baf0906c6696f7a6f5aba"

    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# Frontend
# ------------------------------------------------------------

frontend:
  replicaCount: 2

  image:
    repository: "ghcr.io/ridhampansara27/cloudops-insight-frontend"

    tag: "sha-81bf32d3ecb99cbe500baf0906c6696f7a6f5aba"

    pullPolicy: IfNotPresent


# ------------------------------------------------------------
# Application ingress
# ------------------------------------------------------------

ingress:
  enabled: true

  className: nginx

  host: cloudops.local


# ------------------------------------------------------------
# Development autoscaling
# ------------------------------------------------------------

autoscaling:
  enabled: true

  minReplicas: 2

  maxReplicas: 5

  targetCPUUtilizationPercentage: 70


# ------------------------------------------------------------
# Existing manually-created Kubernetes Secret
# ------------------------------------------------------------

secrets:
  existingSecret: cloudops-secrets
